// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQWpMYkL0-hJxo5e6RbYpZu_pAE-tKFWo',
    appId: '1:167750425566:web:6e83a35a9f273347dedb4f',
    messagingSenderId: '167750425566',
    projectId: 'dream-hunter-c0f89',
    authDomain: 'dream-hunter-c0f89.firebaseapp.com',
    storageBucket: 'dream-hunter-c0f89.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUCYw-9PRPpx8qL2dC5-Yxm4FDXY694og',
    appId: '1:167750425566:android:1200f8f37680fef3dedb4f',
    messagingSenderId: '167750425566',
    projectId: 'dream-hunter-c0f89',
    storageBucket: 'dream-hunter-c0f89.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm55KpIYdt8TnY-TR8tva0lDZM1_Dt0iE',
    appId: '1:167750425566:ios:c47441c5d9c11edadedb4f',
    messagingSenderId: '167750425566',
    projectId: 'dream-hunter-c0f89',
    storageBucket: 'dream-hunter-c0f89.firebasestorage.app',
    iosClientId:
        '167750425566-s4la9ldd3tthgdnh8ufrsgls44r1pvi5.apps.googleusercontent.com',
    iosBundleId: 'com.dreamhunter.dreamhunter',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm55KpIYdt8TnY-TR8tva0lDZM1_Dt0iE',
    appId: '1:167750425566:ios:c47441c5d9c11edadedb4f',
    messagingSenderId: '167750425566',
    projectId: 'dream-hunter-c0f89',
    storageBucket: 'dream-hunter-c0f89.firebasestorage.app',
    iosClientId:
        '167750425566-s4la9ldd3tthgdnh8ufrsgls44r1pvi5.apps.googleusercontent.com',
    iosBundleId: 'com.dreamhunter.dreamhunter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQWpMYkL0-hJxo5e6RbYpZu_pAE-tKFWo',
    appId: '1:167750425566:web:40feb7cf00b41033dedb4f',
    messagingSenderId: '167750425566',
    projectId: 'dream-hunter-c0f89',
    authDomain: 'dream-hunter-c0f89.firebaseapp.com',
    storageBucket: 'dream-hunter-c0f89.firebasestorage.app',
  );
}
